[package]
name = "sic"
version = "0.4.0"
authors = ["foresterre <garm@ilumeo.com>"]
description = "`sic` stands for simple image converter and is a partial front-end for the `image` crate. Specifically it only converts images between certain supported image formats."
license = "MIT"
repository = "https://github.com/foresterre/sic"
exclude = [
    ".idea/*",
    ".vscode/*",
    "imgconv.iml",
]

[dependencies]
clap = "2.32.0"
image = "0.19.0"
combine = "3.3.6"