cargo-features = ["edition"]

[package]
name = "sic"
version = "0.4.0"
authors = ["foresterre <garm@ilumeo.com>"]
description = "`sic` stands for simple image converter and is a partial front-end for the `image` crate. Specifically it only converts images between certain supported image formats."
license = "MIT"
repository = "https://github.com/foresterre/sic"
exclude = [
    ".idea/*",
    ".vscode/*",
    "imgconv.iml",
]
edition = "2018"

[dependencies.clap]
version = "2.27.1"

[dependencies.image]
version = "0.19.0"