[package]
edition = "2018"
name = "sic"
version = "0.10.1"
authors = ["Martijn Gribnau <garm@ilumeo.com>"]
description = "Accessible image processing and conversion from the terminal (and a front-end for the 'image' crate)."
license = "MIT"
repository = "https://github.com/foresterre/sic"
readme = "README.md"
exclude = [
    ".idea/*",
    ".vscode/*",
    "*.iml",
]
keywords = ["image", "converter", "cli", "front-end", "image-cli"]
categories = ["multimedia::images", "command-line-utilities"]

[workspace]
members = [
  "components/sic_cli",
  "components/sic_core",
  "components/sic_image_engine",
  "components/sic_io",
  "components/sic_parser",
  "components/sic_testing",
]

[dependencies]
sic_cli = { path = "components/sic_cli" }

anyhow = "1.0"

[dev-dependencies]
sic_core = { path = "components/sic_core", version = "0.10" }
clap = "2.33.0" # for examples/gen_completions.rs

[build-dependencies]
flate2 = "1.0.14"

[[bin]]
name = "sic"
path = "src/main.rs"

[features]
output-test-images = []

[profile.release]
panic = "abort"
#lto = true
#codegen-units = 1

