[tasks.release]
description = "Prepare release."
dependencies = [ "install_bom" ]
script = [
	"cargo bom > DEP",
	"cargo build --release",
	"rm DEP",
	"touch DEP"
]

[tasks.install_bom]
description = "Installing cargo-bom, but ignoring failure if it, hopefully, is already installed. Either way, since it should be a dependency, always, any task running cargo-bom will fail anyways."
script = [
	"cargo install cargo-bom"	
]
force = true